"""initial_schema

Revision ID: 5a207d9d1f5a
Revises: 
Create Date: 2026-03-05 00:06:29.206245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a207d9d1f5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pwhl_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(length=5), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('arena', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation')
    )
    op.create_index(op.f('ix_pwhl_teams_id'), 'pwhl_teams', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pwhl_game_id', sa.String(), nullable=True),
    sa.Column('season', sa.String(length=9), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('game_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('time_remaining', sa.String(length=10), nullable=True),
    sa.Column('is_overtime', sa.Boolean(), nullable=True),
    sa.Column('is_shootout', sa.Boolean(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['pwhl_teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['pwhl_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_pwhl_game_id'), 'games', ['pwhl_game_id'], unique=True)
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('commissioner_id', sa.Integer(), nullable=True),
    sa.Column('invite_code', sa.String(length=12), nullable=True),
    sa.Column('max_teams', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('draft_type', sa.String(length=20), nullable=True),
    sa.Column('draft_status', sa.String(length=20), nullable=True),
    sa.Column('draft_order', sa.JSON(), nullable=True),
    sa.Column('current_draft_pick', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=9), nullable=True),
    sa.Column('roster_size', sa.Integer(), nullable=True),
    sa.Column('active_roster_size', sa.Integer(), nullable=True),
    sa.Column('ir_slots', sa.Integer(), nullable=True),
    sa.Column('waiver_type', sa.String(length=20), nullable=True),
    sa.Column('trade_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['commissioner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_index(op.f('ix_leagues_id'), 'leagues', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pwhl_player_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('position', sa.String(length=2), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('pwhl_team_id', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('shoots', sa.String(length=1), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('headshot_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pwhl_team_id'], ['pwhl_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_pwhl_player_id'), 'players', ['pwhl_player_id'], unique=True)
    op.create_table('two_factor_setups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('backup_codes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_two_factor_setups_id'), 'two_factor_setups', ['id'], unique=False)
    op.create_table('draft_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_pick_number', sa.Integer(), nullable=True),
    sa.Column('total_picks', sa.Integer(), nullable=True),
    sa.Column('pick_time_limit', sa.Integer(), nullable=True),
    sa.Column('current_pick_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id')
    )
    op.create_index(op.f('ix_draft_sessions_id'), 'draft_sessions', ['id'], unique=False)
    op.create_table('fantasy_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Float(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.Column('waiver_priority', sa.Integer(), nullable=True),
    sa.Column('faab_budget', sa.Float(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fantasy_teams_id'), 'fantasy_teams', ['id'], unique=False)
    op.create_table('game_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('time_in_period', sa.String(length=10), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['pwhl_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_events_game_id'), 'game_events', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_events_id'), 'game_events', ['id'], unique=False)
    op.create_table('league_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('invite_code', sa.String(length=20), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_index(op.f('ix_league_invites_id'), 'league_invites', ['id'], unique=False)
    op.create_table('league_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_members_id'), 'league_members', ['id'], unique=False)
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=9), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.Column('penalty_minutes', sa.Integer(), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('faceoffs_won', sa.Integer(), nullable=True),
    sa.Column('faceoffs_total', sa.Integer(), nullable=True),
    sa.Column('time_on_ice', sa.Float(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('overtime_losses', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('shots_against', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('shutouts', sa.Integer(), nullable=True),
    sa.Column('save_percentage', sa.Float(), nullable=True),
    sa.Column('goals_against_average', sa.Float(), nullable=True),
    sa.Column('fantasy_points', sa.Float(), nullable=True),
    sa.Column('is_season_total', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_stats_id'), 'player_stats', ['id'], unique=False)
    op.create_index(op.f('ix_player_stats_player_id'), 'player_stats', ['player_id'], unique=False)
    op.create_table('scoring_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('goal_pts', sa.Float(), nullable=True),
    sa.Column('assist_pts', sa.Float(), nullable=True),
    sa.Column('plus_minus_pts', sa.Float(), nullable=True),
    sa.Column('pim_pts', sa.Float(), nullable=True),
    sa.Column('shot_pts', sa.Float(), nullable=True),
    sa.Column('hit_pts', sa.Float(), nullable=True),
    sa.Column('block_pts', sa.Float(), nullable=True),
    sa.Column('goalie_win_pts', sa.Float(), nullable=True),
    sa.Column('goalie_save_pts', sa.Float(), nullable=True),
    sa.Column('goals_against_pts', sa.Float(), nullable=True),
    sa.Column('shutout_pts', sa.Float(), nullable=True),
    sa.Column('goalie_loss_pts', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id')
    )
    op.create_index(op.f('ix_scoring_settings_id'), 'scoring_settings', ['id'], unique=False)
    op.create_table('draft_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('fantasy_team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('pick_number', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('pick_in_round', sa.Integer(), nullable=False),
    sa.Column('is_made', sa.Boolean(), nullable=True),
    sa.Column('made_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_picks_id'), 'draft_picks', ['id'], unique=False)
    op.create_index(op.f('ix_draft_picks_league_id'), 'draft_picks', ['league_id'], unique=False)
    op.create_table('fantasy_rosters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fantasy_team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('slot', sa.String(length=20), nullable=True),
    sa.Column('position_slot', sa.String(length=5), nullable=True),
    sa.Column('acquired_via', sa.String(length=20), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fantasy_rosters_fantasy_team_id'), 'fantasy_rosters', ['fantasy_team_id'], unique=False)
    op.create_index(op.f('ix_fantasy_rosters_id'), 'fantasy_rosters', ['id'], unique=False)
    op.create_index(op.f('ix_fantasy_rosters_player_id'), 'fantasy_rosters', ['player_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('proposing_team_id', sa.Integer(), nullable=True),
    sa.Column('receiving_team_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('proposed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['proposing_team_id'], ['fantasy_teams.id'], ),
    sa.ForeignKeyConstraint(['receiving_team_id'], ['fantasy_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_league_id'), 'trades', ['league_id'], unique=False)
    op.create_table('waivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('fantasy_team_id', sa.Integer(), nullable=True),
    sa.Column('player_add_id', sa.Integer(), nullable=True),
    sa.Column('player_drop_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('bid_amount', sa.Float(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_add_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_drop_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waivers_id'), 'waivers', ['id'], unique=False)
    op.create_index(op.f('ix_waivers_league_id'), 'waivers', ['league_id'], unique=False)
    op.create_table('trade_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('from_team_id', sa.Integer(), nullable=True),
    sa.Column('to_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_team_id'], ['fantasy_teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['to_team_id'], ['fantasy_teams.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_items_id'), 'trade_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_items_id'), table_name='trade_items')
    op.drop_table('trade_items')
    op.drop_index(op.f('ix_waivers_league_id'), table_name='waivers')
    op.drop_index(op.f('ix_waivers_id'), table_name='waivers')
    op.drop_table('waivers')
    op.drop_index(op.f('ix_trades_league_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_fantasy_rosters_player_id'), table_name='fantasy_rosters')
    op.drop_index(op.f('ix_fantasy_rosters_id'), table_name='fantasy_rosters')
    op.drop_index(op.f('ix_fantasy_rosters_fantasy_team_id'), table_name='fantasy_rosters')
    op.drop_table('fantasy_rosters')
    op.drop_index(op.f('ix_draft_picks_league_id'), table_name='draft_picks')
    op.drop_index(op.f('ix_draft_picks_id'), table_name='draft_picks')
    op.drop_table('draft_picks')
    op.drop_index(op.f('ix_scoring_settings_id'), table_name='scoring_settings')
    op.drop_table('scoring_settings')
    op.drop_index(op.f('ix_player_stats_player_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_id'), table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index(op.f('ix_league_members_id'), table_name='league_members')
    op.drop_table('league_members')
    op.drop_index(op.f('ix_league_invites_id'), table_name='league_invites')
    op.drop_table('league_invites')
    op.drop_index(op.f('ix_game_events_id'), table_name='game_events')
    op.drop_index(op.f('ix_game_events_game_id'), table_name='game_events')
    op.drop_table('game_events')
    op.drop_index(op.f('ix_fantasy_teams_id'), table_name='fantasy_teams')
    op.drop_table('fantasy_teams')
    op.drop_index(op.f('ix_draft_sessions_id'), table_name='draft_sessions')
    op.drop_table('draft_sessions')
    op.drop_index(op.f('ix_two_factor_setups_id'), table_name='two_factor_setups')
    op.drop_table('two_factor_setups')
    op.drop_index(op.f('ix_players_pwhl_player_id'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_leagues_id'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_games_pwhl_game_id'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pwhl_teams_id'), table_name='pwhl_teams')
    op.drop_table('pwhl_teams')
    # ### end Alembic commands ###
